### ISSUE TITLE
Issue with SKR_modPlugin

### ISSUE THREAD

**Issue by BardezAnAvatar** [MnHebi/SEEKER_UC#1]
Trying to enable Seeker, using latest here for 0.97a (Version 0.5.7M)
- On Steam Deck (Linux)

After the launcher splash screen enabling Seeker, the Starsector loading bar will get to full, then I get a crash:
```
Fatal: Error loading [data.scripts.SKR_modPlugin] Cause: data.scripts.SKR_modPlugin
Check starsector.log for more info
```
log:
```
    at com.fs.starfarer.loading.scripts.ScriptStore$3.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: data.scripts.SKR_modPlugin
   at org.codehaus.janino.JavaSourceClassLoader.findClass(JaveSourceClassLoader.java:179)
   at java.lang.ClassLoader.loadClass(Unknown Source)
   at java.lang.ClassLoader.loadClass(Unknown Source)
   ... 2 more
```

**Comment by MnHebi** [comment]
Please provide the whole log. I assume this is somekind of case sentivity issue.

**Comment by BardezAnAvatar** [comment]
It is. `mod_info.json` references `jar/SEEKER.jar`, archive contains `jar/seeker.jar`

**Comment by MnHebi** [comment]
Thanks, I'll fix that in the next version, in the meantime you can just edit modinfo.

**Comment by MnHebi** [comment]
Recompiled, release updated. Bug fixed.
